name: "aupCTF"
# The name of your CTF


show_challenges: False
# If True, challenges will be shown to the users

scoreboard_frozen: False
# If True, the scoreboard will be frozen, Score will not be updated

ctf_start_time: "2023-06-24T10:00:00"
ctf_end_time: "2023-06-25T22:00:00"
# format: YYYY-MM-DDTHH:MM:SS PST(UTC +5)


categories:
# Uncomment the categories you want to use in your CTF
- OSINT
- Cryptography
- Web
- Forensics
- Stegnography
#- PWN
#- Reverse Engineering
- Misc

tags:
# relivent tags for your CTF (not necessary)
- none