# Generated by Django 4.2 on 2023-05-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('teamname', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
