# Generated by Django 4.2 on 2023-05-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teams_affiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='affiliation',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
