# Generated by Django 4.2 on 2023-06-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_teams_affiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
