# Generated by Django 4.2 on 2023-05-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengessolvedby',
            name='submission_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
