# Generated by Django 4.2 on 2023-05-07 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challengessolvedby_submission_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengessolvedby',
            name='submission_time',
        ),
    ]
