# Generated by Django 4.2 on 2023-05-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_remove_challengessolvedby_submission_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenges',
            old_name='author',
            new_name='author_name',
        ),
        migrations.AddField(
            model_name='challenges',
            name='author_link',
            field=models.URLField(blank=True, default='', max_length=250),
        ),
    ]
