# Generated by Django 4.2 on 2023-05-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_rename_author_challenges_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='hints',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
