# Generated by Django 4.2 on 2023-05-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_challenges_hints'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='difficulty',
            field=models.CharField(default='MEDIUM', max_length=100),
        ),
        migrations.AddField(
            model_name='challenges',
            name='solve_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='flag',
            field=models.CharField(default='CTF{}', max_length=500),
        ),
    ]
