# Generated by Django 4.2 on 2023-05-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_alter_challenges_difficulty_alter_challenges_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
