# Generated by Django 4.2 on 2023-05-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_alter_challenges_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenges',
            name='file',
        ),
    ]
