# Generated by Django 4.2 on 2023-06-10 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_remove_challenges_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengessolvedby',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
