# Generated by Django 4.2 on 2023-06-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_challengessolvedby_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengessolvedby',
            name='first_blood',
            field=models.BooleanField(default=False),
        ),
    ]
