# Generated by Django 4.2 on 2023-06-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_challengessolvedby_first_blood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengessolvedby',
            name='first_blood',
        ),
    ]
