# Generated by Django 4.2 on 2023-06-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0013_challengessolvedby_first_blood'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengessolvedby',
            name='name',
            field=models.CharField(default=None, max_length=250, unique=True),
        ),
    ]
