# Generated by Django 4.2 on 2023-07-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0014_challengessolvedby_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengessolvedby',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
